version: '3.8'

services:
  db:
    image: mongo:7
    container_name: airss-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: airss

  api:
    image: airss:latest
    container_name: airss-api
    restart: always
    command: node api/server.js
    ports:
      - "3001:3001"
    environment:
      - DB_URI=mongodb://db:27017/airss
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_BASE_URL=https://airss-server.seinjian.com
      - UI_BASE_URL=http://localhost:3000
    depends_on:
      - db

  ui:
    image: airss:latest
    container_name: airss-ui
    restart: always
    command: node ui/server.js
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://db:27017/airss
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_BASE_URL=https://airss-server.seinjian.com
      - UI_BASE_URL=http://localhost:3000
    depends_on:
      - api

  worker:
    image: airss:latest
    container_name: airss-worker
    restart: always
    command: node api/rss_worker.js
    environment:
      - DB_URI=mongodb://db:27017/airss
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_BASE_URL=https://airss-server.seinjian.com
      - UI_BASE_URL=http://localhost:3000
    depends_on:
      - api
      - db

volumes:
  mongodata:
